name: docker-build-push

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      NPM_TOKEN: 
        required: true

jobs:
  docker-build-push:
    outputs:
      git_branch_sha_short: ${{ steps.extract_branch.outputs.sha_short }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{  inputs.SERVICE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=raw,value={{branch}}-latest
            type=raw,value={{sha}}

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}