name: docker_build_push

on:
  workflow_call:

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - uses: dopplerhq/cli-action@v2

      # Use doppler PRD token for main
      - name: Login in Doppler and set github action env vars
        if: endsWith(github.ref, '/main')
        run: |
          doppler secrets download --no-file --format=docker >> $GITHUB_ENV;
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRD }}

      # Use doppler DEV token for develop
      - name:  Login in Doppler and set github action env vars
        if: endsWith(github.ref, '/develop')
        run: |
          doppler secrets download --no-file --format=docker >> $GITHUB_ENV;
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_DEV }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{  secrets.SERVICE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=raw,value={{branch}}-latest
            type=raw,value={{sha}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NPM_TOKEN=${{ env.NPM_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}